# These are supported funding model platforms

github: disini
# patreon: disini
# open_collective: disini
# ko_fi: disini
# tidelift: disini
# community_bridge: disini
# liberapay: disini
# issuehunt: disini
# otechie: disini
# custom: https://disini.github.io//three-gpu-pathtracer
